name: Release new Version

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: FreePascal / Lazarus installieren
        run: choco install lazarus --no-progress -y

      - name: Version setzen
        run: |
          $ver="${{ github.ref_name }}".TrimStart("v")
          (Get-Content Vereinsverwaltung.lpi) `
            -replace 'ProductVersion="[^"]+"', "ProductVersion=""$ver.0""" `
            | Set-Content Vereinsverwaltung.lpi

      - name: Neue Release .exe hochladen
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/*.exe
